### ISSUE TITLE
你好，我在retrain的时候遇到一些问题

### ISSUE THREAD

**Issue by Yueziyu** [csdwren/RecDerain#2]
你好，我在使用我自己的数据进行retrain时遇到两个问题，第一个是在使用ssim loss的时候报如下错误：
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    main()
  File "train.py", line 97, in main
    pixel_loss = criterion(target_train, out_train)
  File "/data1/zyyue/anaconda3/envs/NAC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/zyyue/anaconda3/envs/NAC/lib/python3.6/site-packages/pytorch_ssim/__init__.py", line 57, in forward
    return _ssim(img1, img2, window, self.window_size, channel, self.size_average)
  File "/data1/zyyue/anaconda3/envs/NAC/lib/python3.6/site-packages/pytorch_ssim/__init__.py", line 18, in _ssim
    mu1 = F.conv2d(img1, window, padding = window_size/2, groups = channel)
TypeError: conv2d(): argument 'padding' must be tuple of ints, not float
第二个是在我换成mse loss的时候。梯度很快爆炸。
之后我换成了您提供的RaintrainL数据进行相同的retrain实验，同样出现了上面的情况，请问您在实验过程中有出现过这些问题吗？
怎么能解决？

**Comment by csdwren** [comment]
ssim你好像用的是pytorch自带的函数，建议用我提供的 SSIM.py文件里的函数。
梯度爆炸我们没有遇到过，如果用 SSIM.py 也存在梯度爆炸或消失，可以尝试在前几个stage的输出也加上损失函数，给比较小的权重。
